[project]
name = 'governance-token'
description = 'SIP-010 fungible token with built-in governance'
authors = ['BastiatAI']
telemetry = false
cache_dir = './.cache'

[contracts.governance-token]
path = 'contracts/governance-token.clar'
clarity_version = 4
epoch = 3.3

[repl.analysis]
passes = []
